#!/bin/bash

echo ""
echo ""
echo ""
echo ""
echo ""
echo "==============================="
echo "DEV CONTAINER SETUP SUCCESSFULLY!"
echo "==============================="
echo "Starter Environment Vars are setup in .env.local"
echo ""
echo "Don't forget to setup Google Oauth Credentials to enable"
echo "Next-Auth Google Sign on: https://next-auth.js.org/providers/google"
echo ""
echo "Access Couchbase Admin UI @ http://localhost:8091"
echo "User: Administrator"
echo "Pass: password"
echo ""
echo "Start Dev Server with: npm run dev"
echo "Access App @ http://localhost:8091"
echo ""